### ISSUE TITLE
psychsyn_critval output label

### ISSUE THREAD

**Issue by awmeade** [ryentes/careless#32]
The output from psychsyn_critival is great, but the observed correlation in the output is labelled as "Freq".  Consider changing to something like "correlation" or "cor"

**Comment by awmeade** [comment]
actually, i should have made this "cor" instead of "correlation" to be consistent with the output from psychsyn

**Comment by ryentes** [comment]
So we ended up changing the label to "cor" which is consistent with other packages (i.e. stats, psych) and the output of the psychsyn function if diag = TRUE. That said, I'm not opposed to revisiting the naming of a variety of our outputs to ease the experience of users who are not familiar and/or comfortable in R. I think that's part of a larger discussion though.
